@hostname = http://localhost:5556

### Write data
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "write",
    "key": "a_sensor1",
    "Write": {
        "Value": 32242424243333333333.3333
    }
}

### Read data with time range and downsampling
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "read",
    "key": "a_sensor1",
    "Read": {
        "start_timestamp": 1717965210,
        "end_timestamp": 1717965211,
        "downsampling": 3
    }
}

### Read last X records
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "read",
    "key": "a_sensor1",
    "Read": {
        "lastx": 1
    }
}

### Subscribe to a key
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "subscribe",
    "key": "sensor1"
}

### Unsubscribe from a key
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "unsubscribe",
    "key": "sensor1"
}

### Get All keys
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "keys"
}

### Flush all data
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "flush"
}

### Initialize a new key
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "init",
    "key": "new_sensor"
}

### Rename a key
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "renamekey",
    "key": "old_sensor_name",
    "toKey": "new_sensor_name"
}

### Delete a key
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "delete",
    "key": "sensor_to_delete"
}

### Multi-read data with time range and downsampling
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "multi-read",
    "keys": ["sensor1", "sensor2", "sensor3"],
    "Read": {
        "start_timestamp": 1717965210,
        "end_timestamp": 1717965211,
        "downsampling": 3
    }
}

### Multi-read last X records
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "multi-read",
    "keys": ["sensor1", "sensor2", "sensor3"],
    "Read": {
        "lastx": 1
    }
}

### Patch data points for a key
POST {{hostname}}/
Content-Type: application/json

{
    "operation": "data-patch",
    "key": "sensor1",
    "data": "1717965210,123.45\n1717965211,123.46\n1717965212,123.47"
}
